/**
 * GanjaCraft Launcher - esbuild Configuration
 * Бандлинг ES6 модулей для Electron renderer
 */

const esbuild = require('esbuild');
const path = require('path');
const fs = require('fs');

const isWatch = process.argv.includes('--watch');
const isDev = process.argv.includes('--dev');

const buildOptions = {
    entryPoints: [path.join(__dirname, 'src/renderer/app.js')],
    bundle: true,
    outfile: path.join(__dirname, 'src/renderer.bundle.js'),
    format: 'iife',
    platform: 'browser',
    target: ['chrome120'], // Electron 28 uses Chromium 120
    sourcemap: isDev ? 'inline' : false,
    minify: !isDev,
    
    // External - не бандлим, будет из preload
    external: [],
    
    // Define для замены process.env в браузере
    define: {
        'process.env.NODE_ENV': isDev ? '"development"' : '"production"'
    },
    
    // Banner с информацией
    banner: {
        js: `/**
 * GanjaCraft Launcher - Bundled Renderer
 * Auto-generated by esbuild. Do not edit directly.
 * Source: src/renderer/app.js
 * Built: ${new Date().toISOString()}
 */`
    },
    
    // Логирование
    logLevel: 'info',
};

async function build() {
    try {
        if (isWatch) {
            const ctx = await esbuild.context(buildOptions);
            await ctx.watch();
            console.log('👀 Watching for changes...');
        } else {
            const result = await esbuild.build(buildOptions);
            console.log('✅ Bundle built successfully!');
            
            // Показать размер файла
            const stats = fs.statSync(buildOptions.outfile);
            const sizeKB = (stats.size / 1024).toFixed(2);
            console.log(`📦 Output: ${buildOptions.outfile} (${sizeKB} KB)`);
        }
    } catch (error) {
        console.error('❌ Build failed:', error);
        process.exit(1);
    }
}

build();
